Fix chex dependency
Optax does not fix the chex dependency, see [here](https://github.com/deepmind/optax/blob/master/requirements/requirements.txt#L2). 
Currently it will install the newest version 0.1.7 which I believe is incompatible with our jax version, because
I get the following error message:
```
"/algorithmic-efficiency/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/workload.py", line 16, in <module>
    import optax
  File "/usr/local/lib/python3.8/dist-packages/optax/__init__.py", line 17, in <module>
    from optax import experimental
  File "/usr/local/lib/python3.8/dist-packages/optax/experimental/__init__.py", line 20, in <module>
    from optax._src.experimental.complex_valued import split_real_and_imaginary
  File "/usr/local/lib/python3.8/dist-packages/optax/_src/experimental/complex_valued.py", line 32, in <module>
    import chex
  File "/usr/local/lib/python3.8/dist-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/pytypes.py", line 27, in <module>
    ArrayDevice = jax.Array
AttributeError: module 'jax' has no attribute 'Array'
```